stages:
  - prepare
  - test
  - build
  - publish


variables:
  NPM_VERSION_REGEX: /^[~^]?([\dvx*]+(?:[-.](?:[\dx*]+|alpha|beta))*)$/


default:
  tags:
    - docker
  before_script:
    - sed -i -- "s/\"0.0.0\"/\"$CI_COMMIT_TAG\"/g" package.json
    - sed -i -- "s/\"cytomine-client\"/\"@${CI_PROJECT_ROOT_NAMESPACE}\/cytomine-client\"/g" package.json
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

# TODO tests require a full cytomine instance to run, skip for now
# Jenkins tests used to run against a full cytomine but with with fixed versions of components so it was not ideal

build-js-package:
  image: node:14.16.1
  stage: build
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $NPM_VERSION_REGEX
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - dist/cytomine*


publish-js-package:
  image: node:14.16.1
  stage: publish
  if:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $NPM_VERSION_REGEX
  needs:
    - job: build-js-package
      artifacts: true
  script:
    # TODO Push to public npm repo
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - npm publish
