name: Check Quality

on:
  pull_request:
    branches: 
      - main

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install CBIR
        run: python -m poetry install

      - name: Check lint
        run: python -m poetry run pylint cbir tests
