name: Setup Python Poetry
description: Set up a python environment with Poetry

inputs:
  python-version:
    description: The Python version to install
    required: true
  working-directory:
    description: Directory where the script should run
    required: false
    default: "."

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
