stages:
  - prepare
  - build
  - publish


variables:
  DOCKER_IMAGE_NAME: 'cytomine/nginx'
  ENTRYPOINT_SCRIPTS_VERSION: '1.3.0'
  NGINX_VERSION: '1.22.1'

default:
  tags:
    - docker

make-version-name:
  stage: prepare
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/bash:5.2.15-alpine3.16
  script:
    # The
    - | # If no tag has been pushed ($CI_COMMIT_TAG is empty), name it as the branch
      if [ -z $CI_COMMIT_TAG ]; then
        echo "IMAGE_VERSION=$CI_COMMIT_BRANCH" > .env
      else
        # Else use the tag
        echo "IMAGE_VERSION=$CI_COMMIT_TAG" > .env
      fi
    - cat .env
  artifacts:
    reports:
      dotenv: .env


build-push-docker-image:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest
  needs:
    - job: make-version-name
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:

    # Use credential helper (see https://docs.docker.com/engine/reference/commandline/login/#credentials-store)
    - mkdir -p $HOME/.docker && echo $DOCKER_HUB_AUTH_CONFIG > $HOME/.docker/config.json
    - echo "Registry credentials configured at $HOME/.docker/config.json"

    - echo "Build the docker image ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}"
    - |
      docker build \
        --build-arg NGINX_VERSION=${NGINX_VERSION} \
        --build-arg IMAGE_VERSION=${IMAGE_VERSION} \
        --build-arg IMAGE_REVISION=${CI_COMMIT_SHORT_SHA} \
        --build-arg ENTRYPOINT_SCRIPTS_VERSION=${ENTRYPOINT_SCRIPTS_VERSION} \
        -t ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION} \
        -t ${DOCKER_IMAGE_NAME}:latest \
        -f Dockerfile \
        .

    - echo "Pushing docker image ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION} and ${DOCKER_IMAGE_NAME}:latest"
    - docker push ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION}
    - docker push ${DOCKER_IMAGE_NAME}:latest
    - echo "Successfully pushed docker image ${DOCKER_IMAGE_NAME}:${IMAGE_VERSION} and ${DOCKER_IMAGE_NAME}:latest"
