stages:
  - tests

tests:
  stage: tests
  variables:
    IMAGE_NAME: boostrapper-test
  script:
    - docker build -f docker/Dockerfile -t $IMAGE_NAME .
    - docker run -v $(pwd):/code -w /code --entrypoint /bin/bash --rm -it $IMAGE_NAME -c python3 -m unittest discover tests/
