stages:
  - format
  - test
  - publish

unittest:
  stage: test
  tags: 
    - docker
  image: python:3.10-bullseye
  script:
    - python -m pip install -r requirements.txt
    - python -m unittest discover tests/

# format-black:
#   stage: format
#   tags:
#     - docker
#   image:
#     name: cytopia/black
#     entrypoint: ["/bin/ash", "-c"]
#   script:
#     - python3 -m black --check --diff bootstrapper

docker-image:
  stage: publish
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null'
  tags:
    - docker
  image: docker:latest
  script: 
    - docker build -f docker/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

