openapi: 3.1.0
info:
  title: Cytomine Core API
  version: 0.1.0
  description: core API provides requests for core features of Cytomine.

servers:
  - url: http://localhost:8080/api/

tags:
  - name: Annotation
    description: Manage all annotations type
  - name: Legacy user keys
    description: Legacy user keys management

paths:
  /api/annotations/{id}:
    get:
      summary: Get an annotation by ID
      description: |
        Retrieves the annotation with the specified ID from the new annotation service.
        Falls back to the legacy annotation retrieval method if not found.
      tags:
        - Annotation
      operationId: getById
      parameters:
        - $ref: "#/components/parameters/path-annotation-id"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/annotation"
        '404':
          $ref: "#/components/responses/not-found"

  /user/current/keys:
    get:
      summary: Get key pair for current user
      tags:
        - Legacy user keys
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/legacy-user-keys"
    post:
      summary: Regenerate key pair for current user
      description: |
        Previous pair is invalidated.
      tags:
        - Legacy user keys
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/legacy-user-keys"

components:
  parameters:
    account-reference:
      name: id
      in: path
      description: The account reference
      required: true
      schema:
        type: string
        format: uuid
    path-annotation-id:
      name: id
      in: path
      description: The annotation ID
      required: true
      schema:
        type: integer
        format: int64

  responses:
    not-found:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Resource not found"

  schemas:
    annotation:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id-attribute"
        annotationLayer:
          type: integer
          description: The layer to which this annotation belongs.
          format: int64
        location:
          type: string
          format: byte
          description: Binary-encoded annotation geometry data (base64-encoded)
    id-attribute:
      type: integer
      description: The resource identifier
      format: int64
      readOnly: true
    legacy-user-keys:
      type: object
      properties:
        primaryKey:
          type: string
          format: uuid
        secondaryKey:
          type: string
          format: uuid
