openapi: 3.1.0
info:
  title: Cytomine Core API
  version: 0.1.0
  description: core API provides requests for core features of Cytomine.

servers:
  - url: http://localhost:8080/api/

tags:
  - name: Annotation
    description: Manage all annotations type
  - name: Health Check
    description: Health and status server checks
  - name: Legacy user keys
    description: Legacy user keys management

paths:
  /api/annotations/{id}:
    get:
      summary: Get an annotation
      description: |
        Retrieves the annotation with the specified ID from the new annotation service.
        Falls back to the legacy annotation retrieval method if not found.
      tags:
        - Annotation
      operationId: getById
      parameters:
        - $ref: "#/components/parameters/path-annotation-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/annotation"
        "404":
          $ref: "#/components/responses/not-found"

  /api/annotation-layers/{id}/annotations:
    get:
      summary: Get all annotations for an annotation layer
      tags:
        - Annotation
      operationId: getAnnotationsByLayer
      parameters:
        - $ref: "#/components/parameters/path-annotation-layer-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/annotation"

  /api/annotation-layers/{id}/task-run-layer:
    get:
      summary: Get a task run layer for an annotation layer
      tags:
        - Annotation
      operationId: findTaskRunLayer
      parameters:
        - $ref: "#/components/parameters/path-annotation-layer-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task-run-layer"

  /api/image-instances/{id}/annotation-layers:
    get:
      summary: Get all annotation layers for an image instance
      tags:
        - Annotation
      operationId: getAnnotationLayersByImage
      parameters:
        - $ref: "#/components/parameters/path-image-instance-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/annotation-layer"

  /server/ping:
    get:
      summary: Ping the server
      description: Returns server health information.
      tags:
        - Health Check
      operationId: ping
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  alive:
                    type: boolean
                    example: true
                  serverID:
                    type: string
                    example: "default"
                  serverURL:
                    type: string
                    example: "http://127.0.0.1"
                  version:
                    type: string
                    example: "5.2.0"

  /status.json:
    get:
      summary: Check server health status
      description: Returns basic server health information.
      tags:
        - Health Check
      operationId: status
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  alive:
                    type: boolean
                    example: true
                  serverURL:
                    type: string
                    example: "http://127.0.0.1"
                  version:
                    type: string
                    example: "5.2.0"

  /user/current/keys:
    get:
      summary: Get key pair for current user
      tags:
        - Legacy user keys
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/legacy-user-keys"
    post:
      summary: Regenerate key pair for current user
      description: |
        Previous pair is invalidated.
      tags:
        - Legacy user keys
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/legacy-user-keys"

components:
  parameters:
    account-reference:
      name: id
      in: path
      description: The account reference
      required: true
      schema:
        type: string
        format: uuid
    path-annotation-id:
      name: id
      in: path
      description: The annotation identifier
      required: true
      schema:
        type: integer
        format: int64
    path-annotation-layer-id:
      name: id
      in: path
      description: The annotation layer identifier
      required: true
      schema:
        type: integer
        format: int64
    path-image-instance-id:
      name: id
      in: path
      description: The image instance identifier
      required: true
      schema:
        type: integer
        format: int64

  responses:
    not-found:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Resource not found"

  schemas:
    annotation:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/attribute-id"
        annotationLayer:
          type: integer
          description: The layer to which this annotation belongs.
          format: int64
        location:
          type: string
          format: byte
          description: Binary-encoded annotation geometry data (base64-encoded)
    annotation-layer:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/attribute-id"
        name:
          type: string
          description: The name of the annotation layer
    attribute-id:
      type: integer
      description: The resource identifier
      format: int64
      readOnly: true
    legacy-user-keys:
      type: object
      properties:
        primaryKey:
          type: string
          format: uuid
        secondaryKey:
          type: string
          format: uuid
    task-run-layer:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/attribute-id"
        annotationLayer:
          type: integer
          description: The layer to which this annotation belongs.
          format: int64
        image:
          type: integer
          description: The image instance identifier to which this layer belongs.
          format: int64
        taskRun:
          type: integer
          description: The task run identifier to which this layer belongs.
          format: int64
        xOffset:
          type: integer
          description: The x offset of the annotation in the image instance.
          format: int32
        yOffset:
          type: integer
          description: The y offset of the annotation in the image instance.
          format: int32
