apiVersion: apps/v1
kind: Deployment
metadata:
  name: cytomine-core
  labels:
    app: cytomine-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cytomine-core
  template:
    metadata:
      labels:
        app: cytomine-core
      name: cytomine-core
    spec:
      containers:
      - name: cytomine-core
        image: cytomine/core:latest
        ports:
          - containerPort: {{ .Values.cytomineCore.port }}
        env:
        - name: MONGO_DB_NAME
          value: cytomine
        - name: MONGO_HOST
          value: "mongodb.{{ .Release.Namespace }}.svc.cluster.local"
        - name: MONGO_PASS
          value: cytomine
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          value: mongoadmin
        - name: POSTGIS_DB_NAME
          value: cytomine
        - name: POSTGIS_HOST
          value: "postgis.{{ .Release.Namespace }}.svc.cluster.local"
        - name: POSTGIS_PASS
          value: cytomine
        - name: POSTGIS_PORT
          value: "5432"
        - name: POSTGIS_USER
          value: cytomine
---
apiVersion: v1
kind: Service
metadata:
  name: cytomine-core
spec:
  selector:
    name: cytomine-core
  ports:
  - name: cytomine-core-port
    protocol: TCP
    port: {{ .Values.cytomineCore.port }}

