apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: {{ .Values.cytomineCore.port }}
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx
  ports:
  - name: nginx-port
    protocol: TCP
    port: {{ .Values.cytomineCore.port }}

