apiVersion: v1
kind: Pod
metadata:
  labels:
    name: postgis
  name: postgis
spec:
  containers:
  - name: postgis
    image: cytomine/postgis:latest
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: cytomine
    - name: POSTGRES_DB
      value: cytomine
    - name: POSTGRES_USER
      value: cytomine
---
apiVersion: v1
kind: Service
metadata:
  name: postgis-service
spec:
  selector:
    name: postgis
  ports:
  - protocol: TCP
    port: 5432

