apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
      name: postgis
    spec:
      containers:
      - name: postgis
        image: cytomine/postgis:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: cytomine
        - name: POSTGRES_USER
          value: cytomine
        - name: POSTGRES_NAME
          value: cytomine
---
apiVersion: v1
kind: Service
metadata:
  name: postgis-service
spec:
  selector:
    app: postgis
  ports:
  - protocol: TCP
    port: 5432

