apiVersion: v1
kind: Service
metadata:
  name: cytomine-core-service
spec:
  selector:
    name: cytomine-core
  ports:
  - name: cytomine-core-port
    protocol: TCP
    port: {{ .Values.cytomineCore.port }}
    targetPort: http-web-svc
